services:
  app:
    build: .
    ports:
      - "1010:1010"
    volumes:
      - ./:/app
      - /app/vendor
    working_dir: /app
    command: sh -c "php bin/console cache:clear && php -S 0.0.0.0:1010 -t public/"