      - name: Commitar e Fazer Push dos Resultados
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Verifica se a pasta existe, se não, cria para evitar erro de comando
          mkdir -p kaykewf13/SUGOIAPI/output/
          
          # Adiciona apenas o que existir, sem dar erro fatal
          git add kaykewf13/SUGOIAPI/output/*.csv || echo "Nenhum CSV encontrado"
          git add kaykewf13/SUGOIAPI/output/*.xlsx || echo "Nenhum XLSX encontrado"
          git add kaykewf13/SUGOIAPI/output/*.m3u || echo "Nenhum M3U encontrado"
          
          # Verifica se há algo novo para commitar
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update: Relatórios [$(date +'%Y-%m-%d %H:%M')]"
            git push
          else
            echo "Nada para atualizar hoje."
          fi
